name: Website Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-website:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
      - run: npm install --production=false
        # if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run docs:build
      - run: npm install @serverless-devs/s -g
      - run: s config add --AccountID ${{secrets.ALIYUN_ACCOUNT_ID}} --AccessKeyID ${{secrets.ALIYUN_ACCESS_KEY_ID}} --AccessKeySecret ${{secrets.ALIYUN_ACCESS_KEY_SECRET}} -a shl -f
      - run: s deploy --use-local -y
      - name: Sync docs to xsahxl.github.io
        run: ./scripts/sync.sh
